### ISSUE TITLE
Help needed for contribution

### ISSUE THREAD

**Issue by N0rbi** [andresavic/AmongKey#27]
Hi @andresavic could you please create a brief guide / wiki on how you created the [AmongUsClassifier.mlmodel](https://github.com/andresavic/AmongKey/blob/main/AmongKey/AmongUsClassifier.mlmodel) file? I'm interested in the input dataset and the expected output of the model. I would like to make a PR with the updated UI of among us.

Thank you

**Comment by andresavic** [comment]
Hello @N0rbi, Thank you very much for your interest in contributing. You can find the whole dataset here: https://drive.google.com/drive/folders/1VP8d5Rle5NWI-30EeXDdZ-mcO3Q3CSVI

A guide how to train the model can be found here: https://developer.apple.com/documentation/createml/creating-an-image-classifier-model
Its a straightforward process.

In order to collect trainings data there is a functionality implemented to store the screenshots in the correct folder by pressing number keys:
https://github.com/andresavic/AmongKey/blob/cf393332aab1b98b61de3fd0df9b2dbe2579b067/AmongKey/AmongKeyApp.swift#L189

https://github.com/andresavic/AmongKey/blob/cf393332aab1b98b61de3fd0df9b2dbe2579b067/AmongKey/Keymapping.swift#L94

Let me know if you have any further questions.

Best,
Andre

**Comment by N0rbi** [comment]
Thank you for guiding me through. This helped me a lot in starting out.

This should be useful to the problem mentioned in #28 but since chat is not a game breaking feature, I think it would be a minor improvement.
